# -*- coding: utf-8 -*-

{
  'Italie' => {
    'Abruzzes' => [
      'Alto Tirino',
      'Colli Aprutini',
      'Colli del Sangro',
      'Colline Frentane',
      'Colline Pescaresi',
      'Colline Teatine',
      'Controguerra',
      'Del Vastese / Histonium',
      "Montepulciano d'Abruzzo",
      "Montepulciano d'Abruzzo Colline Teramane",
      'Terre Di Chieti',
      "Trebbiano d'Abruzzo",
      'Valle Peligna'
    ],
    'Basilicat' => [
      'Aglianico del Vulture',
      'Basilicata'
    ],
    'Frioul-Venezia Giulia' => [
      'Carso',
      'Colli Orientali del Friuli (Cialla, Ramandolo, Rosazzo)',
      'Collio Goriziano / Collio',
      'Friuli Annia',
      'Friuli Aquileia',
      'Friuli Grave',
      'Friuli Isonzo',
      'Friuli Latisana',
      'Lison-Pramaggiore',
      'Alto Livenza',
      'Venezia Giulia',
      'Venezie / Delle Venezie'
    ],
    'Calabre' => [
      'Bivongi',
      'Cirò',
      'Donnici',
      'Greco di Bianco',
      'Lamezia',
      'Melissa',
      'Pollino',
      "Sant'Anna di Isola Capo Rizzuto",
      'San Vito di Luzzi',
      'Savuto',
      'Scavigna',
      'Verbicaro',
      'Arghillà',
      'Calabria',
      'Condoleo',
      'Costa Viola',
      'Esaro',
      'Lipuda',
      'Locride',
      'Palizzi',
      'Pellaro',
      'Scilla',
      'Val di Neto',
      'Valdamato',
      'Valle del Crati'
    ],
    'Campanie' => [
      'Aglianico del Taburno',
      'Aversa',
      'Campi Flegrei',
      'Capri',
      'Castel San Lorenzo',
      'Cilento',
      "Costa d'Amalfi",
      'Falerno del Massico',
      'Fiano di Avellino',
      'Galluccio',
      'Greco di Tufo',
      'Guardia Sanframondi / Guardiolo',
      'Ischia',
      'Penisola Sorrentina',
      'Sannio',
      "Sant'Agata de Goti",
      'Solopaca',
      'Taburno',
      'Vesuvio',
      'Beneventano',
      'Colli di Salerno',
      'Dugenta',
      'Epomeo',
      'Irpinia',
      'Paestum',
      'Pompeiano',
      'Roccamonfina',
      'Terre del Volturno'
    ],
    'Emilia-Romagne' => [
      'Bosco Eliceo',
      'Cagnina di Romagna',
      'Colli Bolognesi (Colline di Oliveto, Colline di Riosto, Colline Marconiane, Monte San Pietro, Serravalle, Zola Predosa)',
      'Colli Bolognesi Classico Pignoletto',
      'Colli di Faenza',
      'Colli di Imola',
      'Colli di Parma',
      'Colli di Rimini',
      'Colli di Scandiano e di Canossa',
      'Colli Piacentini (Gutturnio, Monterosso Val d’Arda, Trebbianino Val Trebbia)',
      'Lambrusco di Sorbara',
      'Lambrusco Grasparossa di Castelvetro',
      'Lambrusco Salamino di Santa Croce',
      'Pagadebit di Romagna (Bertinoro)',
      'Reggiano',
      'Reno',
      'Romagna Albana Spumante',
      'Sangiovese di Romagna',
      'Trebbiano di Romagna',
      'Bianco di Castelfranco Emilia',
      "Emilia or dell'Emilia",
      'Fontana del Taro',
      'Forlì',
      'Modena or Provincia di Modena',
      'Ravenna',
      'Rubicone',
      'Sillaro or Bianco di Sillaro',
      'Terre di Veleja',
      'Val Tidone'
    ],
    'Latium' => [
      'Aleatico di Gradoli',
      'Aprilia',
      'Atina',
      'Bianco Capena',
      'Castelli Romani',
      'Cerveteri',
      'Cesanese del Pigio / Piglio',
      'Cesanese di Affile / Affile',
      'Cesanese di Olevano Romano / Olevano Romano',
      'Circeo',
      'Colli Albani',
      'Colli della Sabina',
      'Colli Etruschi Viterbesi',
      'Colli Lanuvini',
      'Cori',
      'Est! Est!! Est!!! di Montefiascone',
      'Frascati',
      'Genazzano',
      'Marino',
      'Montecompatri Colonna',
      'Orvieto',
      'Tarquinia',
      'Velletri',
      'Vignanello',
      'Zagarolo',
      "Civitella d'Agliano",
      'Colli Cimini',
      'Frusinante',
      'Lazio',
      'Nettuno'
    ],
    'Ligurie' => [
      'Cinque Terre (Costa de Sera, Costa de Campu, Costa da Posa)',
      'Cinque Terre Sciacchetrà',
      'Colli di Luni',
      'Colline di Levanto',
      'Golfo del Tigullio',
      'Riviera Ligure di Ponente (Albenga, Finale, Riviera dei Fiori)',
      'Rossese di Dolceacqua / Dolceacqua',
      'Val Polcevera',
      'Colline Savonesi'
    ],
    'Lombardie' => [
      'Botticino',
      'Capriano del Colle',
      'Cellatica',
      'Garda',
      'Garda Bresciano',
      'Garda Colli Mantovani',
      'Lambrusco Mantovano',
      'Lugana',
      'Oltrepò Pavese',
      'San Colombano al Lambro',
      'San Martino della Battaglia',
      'Terre di Franciacorta',
      'Valcalepio',
      'Valtellina',
      'Alto Mincio',
      'Benaco Bresciano',
      'Bergamasca',
      'Collina del Milanese',
      'Mantova / Provincia di Mantova',
      'Montenetto di Brescia',
      'Pavia / Provincia di Pavia',
      'Quistello',
      'Ronchi di Brescia',
      'Sabbioneta',
      'Sebino',
      'Terrazze Retiche di Sondrio'
    ],
    'Marches' => [
      'Bianchello del Metauro',
      'Colli Maceratesi',
      'Colli Pesaresi',
      'Esino',
      'Falerio dei Colli Ascolani',
      'Lacrima di Morro',
      'Rosso Conero',
      'Rosso Piceno',
      'Verdicchio dei Castelli di Jesi (Classico)',
      'Verdicchio di Matelica',
      'Vernaccia di Serrapetrona',
      'Marche'
    ],
    'Molise' => [
      'Biferno',
      'Molise',
      'Pentro di Isernia',
      'Osco / Terre degli Osci',
      'Rotae'
    ],
    'Ombrie' => [
      'Assisi',
      'Colli Altotiberini',
      'Colli Amerini',
      'Colli del Trasimeno / Trasimeno',
      'Colli Martani',
      'Colli Perugini',
      'Lago di Corbara',
      'Montefalco',
      'Orvieto / Orvieto Classico',
      'Rosso Orvietano / Orvietano Rosso',
      'Torgiano',
      'Allerona',
      'Bettona',
      'Cannara',
      'Narni',
      'Spello',
      'Umbria'
    ],
    'Piemont' => [
      'Asti',
      'Barbaresco',
      'Barolo',
      "Brachetto d'Acqui",
      'Gattinara',
      'Gavi / Cortese di Gavi',
      'Ghemme',
      'Albugnano',
      "Barbera d'Alba",
      "Barbera d'Asti",
      'Barbera del Monferrato',
      'Boca',
      'Bramaterra',
      'Canavese',
      'Carema',
      'Colli Tortonesi',
      'Colline Novaresi',
      'Colline Saluzzesi',
      'Colline Torinesi',
      "Cortese dell'Alto Monferrato",
      'Coste della Sesia',
      "Dolcetto d'Acqui",
      "Dolcetto d'Alba",
      "Dolcetto d'Asti",
      'Dolcetto delle Langhe Monregalesi',
      "Dolcetto di Diano d'Alba / Diano d’Alba",
      'Dolcetto di Dogliani',
      'Dolcetto di Ovada',
      'Erbaluce di Caluso',
      'Fara',
      "Freisa d'Asti",
      'Freisa di Chieri',
      'Gabiano',
      "Grignolino d'Asti",
      'Grignolino del Monferrato Casalese',
      'Langhe',
      'Lessona',
      'Loazzolo',
      "Malvasia di Casorzo d'Asti",
      'Malvasia di Castelnuovo Don Bosco',
      'Monferrato (Casalese)',
      "Nebbiolo d'Alba",
      'Piemonte',
      'Pinerolese',
      'Roero',
      'Rubino di Cantavenna',
      'Ruchè di Castagnole Monferrato',
      'Sizzano',
      'Valsusa',
      'Verduno Pelaverga / Verduno'
    ],
    'Pouilles' => [
      'Aleatico di Puglia',
      'Alezio',
      'Brindisi',
      "Cacc'e mmitte di Lucera",
      'Castel del Monte',
      'Copertino',
      'Galatina',
      'Gioia del Colle',
      'Gravina',
      'Leverano',
      'Lizzano',
      'Locorotondo',
      'Martina / Martina Franca',
      'Matino',
      'Moscato di Trani',
      'Nardò',
      'Orta Nova',
      'Ostuni',
      'Primitivo di Manduria',
      'Rosso Barletta',
      'Rosso Canosa',
      'Rosso di Cerignola',
      'Salice Salentino',
      'San Severo',
      'Squinzano',
      'Daunia',
      'Murgia',
      'Puglia',
      'Salento',
      'Tarantino',
      "Valle d'Itria"
    ],
    'Sardaigne' => [
      'Vermentino di Gallura',
      'Alghero',
      'Arborea',
      'Campidano di Terralba',
      'Cannonau di Sardegna (Capo Ferrato, Jerzu, Oliena or Nepente di Oliena)',
      'Carignano del Sulcis',
      'Girò di Cagliari',
      'Malvasia di Bosa',
      'Malvasia di Cagliari',
      'Mandrolisai',
      'Monica di Cagliari',
      'Monica di Sardegna',
      'Moscato di Cagliari',
      'Moscato di Sardegna (Gallura, Tempio Pausania)',
      'Moscato di Sorso Sennori',
      'Nasco di Cagliari',
      'Nuragus di Cagliari',
      'Sardegna Semidano (Mogoro)',
      'Vermentino di Sardegna',
      'Vernaccia di Oristano',
      'Barbagia',
      'Camarro',
      'Colli del Limbara',
      'Isola dei Nuraghi',
      'Marmilla',
      'Nurra',
      'Ogliastra',
      'Parteolla',
      'Planargia',
      'Nuoro / Provincia di Nuoro',
      'Romangia',
      'Sibiola',
      'Tharros',
      'Trexenta',
      'Valle del Tirso',
      'Valli di Porto Pino'
    ],
    'Sicile' => [
      'Alcamo',
      'Cerasuolo di Vittoria',
      'Contea di Sclafani',
      'Contessa Entellina',
      'Delia Nivolelli',
      'Eloro',
      'Etna',
      'Faro',
      'Malvasia delle Lipari',
      'Marsala',
      'Menfi',
      'Monreale',
      'Moscato di Noto',
      'Moscato di Pantelleria',
      'Moscato Passito di Pantelleria',
      'Moscato di Siracusa',
      'Sambuca di Sicilia',
      'Santa Margherita di Belice',
      'Sciacca',
      'Colli Ericini',
      'Fontanarossa di Cerda',
      'Salemi',
      'Salina',
      'Sicilia',
      'Valle Belic'
    ],
    'Toscane' => [
      'Brunello di Montalcino',
      'Carmignano Rosso Riserva',
      'Chianti (Colli Aretini, Colli Fiorentini, Colli Senesi, Colline Pisane, Montalbano, Montespertoli, Rufina)',
      'Chianti Classico',
      'Vernaccia di San Gimignano',
      'Vino Nobile di Montepulciano',
      "Ansonica Costa dell'Argentario",
      'Barco Reale di Carmignano',
      'Bianco della Valdinievole',
      "Bianco dell'Empolese",
      'Bianco di Pitigliano',
      'Bianco Pisano di San Torpè',
      'Bolgheri (Sassicaia)',
      'Candia dei Colli Apuani',
      'Capalbio',
      'Carmignano',
      "Colli dell'Etruria Centrale",
      'Colli di Luni',
      'Colline Lucchesi',
      'Cortona',
      'Elba',
      'Montecarlo',
      'Montecucco',
      'Monteregio di Massa Marittima',
      'Montescudaio',
      'Morellino di Scansano',
      'Moscadello di Montalcino',
      'Orcia',
      'Parrina',
      'Pomino',
      'Rosso di Montalcino',
      'Rosso di Montepulciano',
      'San Gimignano',
      "Sant'Antimo",
      'Sovana',
      "Val d'Arbia",
      'Valdichiana',
      'Val di Cornia (Campiglia Marittima, Piombino, San Vincenzo, Suvereto)',
      'Vin Santo del Chianti (Colli Aretini, Colli Fiorentini, Colli Senesi, Colline Pisane, Montalbano, Montespertoli, Rufina)',
      'Vin Santo del Chianti Classico',
      'Vin Santo di Montepulciano',
      'Alta Valle della Greve',
      'Colli della Toscana Centrale',
      'Maremma Toscana',
      'Toscana / Toscano',
      'Val di Magra'
    ],
    'Trentino-Haut-Adige' => [
      'Alto Adige / Südtirol / Sudtirolo',
      'Caldaro / Kalterer',
      'Casteller',
      'Teroldego Rotaliano',
      'Trentino (Sorni)',
      'Trento',
      'Valdadige / Etschtaler',
      'Mitterberg',
      'Vallagarina',
      'Venezie',
      'Vigneti delle Dolomiti'
    ],
    "Val d'Aoste" => [
      "Valle d'Aosta"
    ],
    'Venetie' => [
      'Bardolino Superiore (Classico)',
      'Recioto di Soave (Classico)',
      'Arcole',
      'Bagnoli di Sopra (Classico)',
      'Bardolino (Classico)',
      'Bianco di Custoza',
      'Breganze',
      'Colli Berici',
      'Colli di Conegliano',
      'Colli Euganei',
      'Gambellara (Classico)',
      'Garda',
      'Lessini Durello',
      'Lison-Pramaggiore',
      'Lugana',
      'Montello e Colli Asolani',
      'Piave',
      'Prosecco di Conegliano Valdobbiadene',
      'Recioto della Valpolicella (Classico, Valpantena)',
      'San Martino della Battaglia',
      'Soave (Classico)',
      'Valpolicella (Classico, Valpantena, Amarone della Valpolicella)',
      'Valdadige',
      'Alto Livenza',
      'Colli Trevigiani',
      'Conselvano',
      'Marca Trevigiana',
      'Vallagarina',
      'Veneto',
      'Veneto Orientale',
      'Veronese / Provincia di Verona',
      'Venezie',
      'Vigneti delle Dolomiti'
    ]
  }
}.each do |s_country, regions|
  country = Country.find_or_create_by_name(s_country)
  regions.each do |s_region, areas|
    region = Region.find_or_create_by_name(s_region)
    region.country =  country
    region.save
    areas.each do |s_area|
      area = Area.find_or_create_by_name(s_area)
      area.region = region
      area.save
    end
  end
end

