# -*  'coding: utf-8 -*-

[
  'Abondance',
  'Abouriou',
  'Aligoté',
  'Altesse',
  'Amigne',
  'Arvine',
  'Auxerrois',
  'Bachet',
  'Bourboulenc',
  'Cabernet franc',
  'Cabernet-sauvignon',
  'Carignan',
  'Chardonnay',
  'Chasselas',
  'Chenin',
  'Cinsaut',
  'Clairette',
  'Clarin',
  'Colombard',
  'Côt',
  'Duras',
  'Furmint',
  'Gamay',
  'Gewürztraminer',
  'Grenache',
  'Gros Manseng',
  'Gros Verdot',
  'Humagne blanche',
  'Humagne rouge',
  'Jurançon blanc',
  'Jurançon noir',
  'Len de l\'el',
  'Lignan blanc',
  'Lledoner pelut',
  'Macabeu',
  'Malbec',
  'Manseng',
  'Marsanne',
  'Mauzac',
  'Merlot blanc',
  'Merlot noir',
  'Meunier',
  'Mondeuse blanche',
  'Mondeuse noire',
  'Mourvèdre',
  'Müller-Thurgau',
  'Muscadelle',
  'Muscat à petits grains',
  'Muscat d\'Alexandrie',
  'Muscat Ottonel',
  'Nebbiolo',
  'Ondenc',
  'Petit Manseng',
  'Petit Verdot',
  'Pineau d\'Aunis',
  'Pinot blanc',
  'Pinot gris',
  'Pinot noir',
  'Piquepoul',
  'Poulsard',
  'Riesling',
  'Rolle',
  'Roussanne',
  'Rousse',
  'Roussette d\'Ayze',
  'Sangiovese',
  'Sauvignon',
  'Savagnin',
  'Sémillon',
  'Sylvaner',
  'Syrah',
  'Tannat',
  'Trousseau',
  'Ugni blanc et rose',
  'Viognier',
  'Zinfandel',
].each do |c_name|
  c = GrapeVariety.find_or_create_by_name(c_name)
  c.validation = true
  c.save
end
