# -*- coding: utf-8 -*-

{
  'France' => {
    'Alsace' => [
      'Alsace Gewürztraminer',
      'Alsace Grand Cru',
      'Alsace Klevner de Heiligenstein',
      'Alsace Klevner',
      'Alsace Muscat',
      'Alsace Pinot Noir',
      'Alsace Riesling',
      'Alsace Sylvaner',
      'Alsace Pinot Gris',
      "Crémant d'Alsace",
      'Alsace Edelzwicker',
      'Alsace Pinot Blanc',
      'Alsace',
      'Alsace Chasselas',
      'Alsace Auxerrois'
    ],
    'Bordeaux' => [
      'Barsac',
      'Blaye',
      'Bordeaux',
      'Bordeaux Côtes de Francs',
      'Bordeaux Haut-Benauge',
      'Bordeaux Supérieur',
      'Cadillac',
      'Canon-Fronsac',
      'Cérons',
      'Côtes de Blaye',
      'Côtes de Bordeaux',
      'Côtes de Bordeaux St Macaire',
      'Côtes de Bourg',
      'Côtes de Castillon',
      'Crémant de Bordeaux',
      'Entre-deux-mers',
      'Entre-deux-mers Haut Benauge',
      'Fronsac',
      'Graves',
      'Graves de Vayres',
      'Graves Supérieures',
      'Haut-Médoc',
      'Lalande de Pomerol',
      'Listrac-Médoc',
      'Loupiac',
      'Lussac-Saint-Emilion',
      'Margaux',
      'Médoc',
      'Montagne-Saint-Emilion',
      'Moulis-en-Médoc',
      'Pauillac',
      'Pessac-Léognan',
      'Pomerol',
      'Premières Côtes de Blaye',
      'Premières Côtes de Bordeaux',
      'Puisseguin-Saint-Emilion',
      'Sainte Croix du Mont',
      'Sainte Foy de Bordeaux',
      'Saint-Emilion',
      'Saint-Emilion Grand Cru',
      'Saint-Estèphe',
      'Saint-Georges-Saint-Emilion',
      'Saint-Julien',
      'Sauternes',
      "Vin de Pays de l'Atlantique"
    ],
    'Bourgogne' => [
      'Aloxe-Corton',
      'Auxey-Duresses',
      'Bâtard-Montrachet',
      'Beaune',
      'Bienvenues-Bâtard-Montrachet',
      'Blagny',
      'Bonnes-Mares',
      'Bourgogne',
      'Bourgone Aligoté',
      'Bourgogne Chitry',
      'Bourgogne Côte Chalonnaise',
      "Bourgogne Côtes d'Auxerre",
      'Bourgogne Côtes du Couchois',
      'Bourgogne Coulanges la Vineuse',
      'Bourgogne Epineuil',
      'Bourgogne Hautes Côtes de Beaune',
      'Bourgogne Hautes Côtes de Nuits',
      'Bourgogne Mousseux',
      'Bourgogne Ordinaire',
      'Bourgogne Grand Ordinaire',
      'Bourgogne Passe Tout Grains',
      'Bourgogne Vezelay',
      'Bouzeron',
      'Chablis',
      'Chablis Grand Cru',
      'Chambertin',
      'Chambertin Clos de Beze',
      'Chambolle-Musigny',
      'Chapelle-Chambertin',
      'Chassagne-Montrachet',
      'Chevalier-Montrachet',
      'Chorey-Lès-Beaune',
      'Clos de la Roche',
      'Clos des Lambrays',
      'Clos de Tart',
      'Clos de Vougeot',
      'Clos Saint-Denis',
      'Corton',
      'Corton-Charlemagne',
      'Côte de Beaune',
      'Côte de Beaune Villages',
      'Côte de Brouilly',
      'Côtes de Nuits Villages',
      'Crémant de Bourgogne',
      'Criots-Bâtard-Montrachet',
      'Echezeaux',
      'Fixin',
      'Gevrey-Chambertin',
      'Grands Echezeaux',
      'Griotte-Chambertin',
      'Irancy',
      'Ladoix',
      'La Grande Rue',
      'La Romanée',
      'La Tache',
      'Latricières-Chambertin',
      'Mâcon',
      'Mâcon Villages',
      'Maranges',
      'Marsannay',
      'Mazis-Chambertin',
      'Mazoyères-Chambertin',
      'Mercurey',
      'Meursault',
      'Montagny',
      'Monthélie',
      'Montrachet',
      'Morey-Saint-Denis',
      'Musigny',
      'Nuits-Saint-Georges',
      'Pernand-Vergelesses',
      'Petit Chablis',
      'Pommard',
      'Pouilly-Fuissé',
      'Pouilly-Loche',
      'Pouilly-Vinzelles',
      'Puligny-Montrachet',
      'Richebourg',
      'Romanée-Conti',
      'Romanée-Saint-Vivant',
      'Ruchottes-Chambertin',
      'Rully',
      'Saint-Aubin',
      'Saint-Bris',
      'Saint-Romain',
      'Saint-Véran',
      'Santenay',
      'Savigny-Lès-Beaune',
      'Viré-Clessé',
      'Volnay',
      'Volnay-Santenots',
      'Vosne-Romanée',
      'Vougeot',
      "Vin de Pays de l'Yonne"
    ]
  }
}.each do |s_country, regions|
  country = Country.find_or_create_by_name(s_country)
  regions.each do |s_region, areas|
    region = Region.find_or_create_by_name(s_region)
    region.country =  country
    region.save
    areas.each do |s_area|
      area = Area.find_or_create_by_name(s_area)
      area.region = region
      area.save
      puts "#{country.name}(#{country.id}) - #{region.name}(#{region.id}) - #{area.name}(#{area.id})"
    end
  end
end

