# -*- coding: utf-8 -*-

{
  'France' => {
    'Alsace' => [
      'Alsace Gewürztraminer',
      'Alsace Grand Cru',
      'Alsace Klevner de Heiligenstein',
      'Alsace Klevner',
      'Alsace Muscat',
      'Alsace Pinot Noir',
      'Alsace Riesling',
      'Alsace Sylvaner',
      'Alsace Pinot Gris',
      "Crémant d'Alsace",
      'Alsace Edelzwicker',
      'Alsace Pinot Blanc',
      'Alsace',
      'Alsace Chasselas',
      'Alsace Auxerrois'
    ],
    'Bordeaux' => [
      'Barsac',
      'Blaye',
      'Bordeaux',
      'Bordeaux Côtes de Francs',
      'Bordeaux Haut-Benauge',
      'Bordeaux Supérieur',
      'Cadillac',
      'Canon-Fronsac',
      'Cérons',
      'Côtes de Blaye',
      'Côtes de Bordeaux',
      'Côtes de Bordeaux St Macaire',
      'Côtes de Bourg',
      'Côtes de Castillon',
      'Crémant de Bordeaux',
      'Entre-deux-mers',
      'Entre-deux-mers Haut Benauge',
      'Fronsac',
      'Graves',
      'Graves de Vayres',
      'Graves Supérieures',
      'Haut-Médoc',
      'Lalande de Pomerol',
      'Listrac-Médoc',
      'Loupiac',
      'Lussac-Saint-Emilion',
      'Margaux',
      'Médoc',
      'Montagne-Saint-Emilion',
      'Moulis-en-Médoc',
      'Pauillac',
      'Pessac-Léognan',
      'Pomerol',
      'Premières Côtes de Blaye',
      'Premières Côtes de Bordeaux',
      'Puisseguin-Saint-Emilion',
      'Sainte Croix du Mont',
      'Sainte Foy de Bordeaux',
      'Saint-Emilion',
      'Saint-Emilion Grand Cru',
      'Saint-Estèphe',
      'Saint-Georges-Saint-Emilion',
      'Saint-Julien',
      'Sauternes',
      "Vin de Pays de l'Atlantique"
    ],
    'Bourgogne' => [
      'Aloxe-Corton',
      'Auxey-Duresses',
      'Bâtard-Montrachet',
      'Beaune',
      'Bienvenues-Bâtard-Montrachet',
      'Blagny',
      'Bonnes-Mares',
      'Bourgogne',
      'Bourgone Aligoté',
      'Bourgogne Chitry',
      'Bourgogne Côte Chalonnaise',
      "Bourgogne Côtes d'Auxerre",
      'Bourgogne Côtes du Couchois',
      'Bourgogne Coulanges la Vineuse',
      'Bourgogne Epineuil',
      'Bourgogne Hautes Côtes de Beaune',
      'Bourgogne Hautes Côtes de Nuits',
      'Bourgogne Mousseux',
      'Bourgogne Ordinaire',
      'Bourgogne Grand Ordinaire',
      'Bourgogne Passe Tout Grains',
      'Bourgogne Vezelay',
      'Bouzeron',
      'Chablis',
      'Chablis Grand Cru',
      'Chambertin',
      'Chambertin Clos de Beze',
      'Chambolle-Musigny',
      'Chapelle-Chambertin',
      'Chassagne-Montrachet',
      'Chevalier-Montrachet',
      'Chorey-Lès-Beaune',
      'Clos de la Roche',
      'Clos des Lambrays',
      'Clos de Tart',
      'Clos de Vougeot',
      'Clos Saint-Denis',
      'Corton',
      'Corton-Charlemagne',
      'Côte de Beaune',
      'Côte de Beaune Villages',
      'Côte de Brouilly',
      'Côtes de Nuits Villages',
      'Crémant de Bourgogne',
      'Criots-Bâtard-Montrachet',
      'Echezeaux',
      'Fixin',
      'Gevrey-Chambertin',
      'Grands Echezeaux',
      'Griotte-Chambertin',
      'Irancy',
      'Ladoix',
      'La Grande Rue',
      'La Romanée',
      'La Tache',
      'Latricières-Chambertin',
      'Mâcon',
      'Mâcon Villages',
      'Maranges',
      'Marsannay',
      'Mazis-Chambertin',
      'Mazoyères-Chambertin',
      'Mercurey',
      'Meursault',
      'Montagny',
      'Monthélie',
      'Montrachet',
      'Morey-Saint-Denis',
      'Musigny',
      'Nuits-Saint-Georges',
      'Pernand-Vergelesses',
      'Petit Chablis',
      'Pommard',
      'Pouilly-Fuissé',
      'Pouilly-Loche',
      'Pouilly-Vinzelles',
      'Puligny-Montrachet',
      'Richebourg',
      'Romanée-Conti',
      'Romanée-Saint-Vivant',
      'Ruchottes-Chambertin',
      'Rully',
      'Saint-Aubin',
      'Saint-Bris',
      'Saint-Romain',
      'Saint-Véran',
      'Santenay',
      'Savigny-Lès-Beaune',
      'Viré-Clessé',
      'Volnay',
      'Volnay-Santenots',
      'Vosne-Romanée',
      'Vougeot',
      "Vin de Pays de l'Yonne"
    ],
    'Champagne' => [
      'Champagne',
      'Champagne Grand Cru',
      'Côteaux Champenois',
      'Rosé des Riceys'
    ],
    'Jura' => [
      'Arbois',
      'Arbois-Pupillin',
      'Château-Châlon',
      'Côtes du Jura',
      'Crémant du Jura',
      "L'Etoile",
      'Macvin du Jura',
      'Vin de Pays de la Haute-Marne',
      'Vin de Pays de la Haute-Saône',
      'Vin de Pays de la Saône-et-Loire',
      'Vin de Pays de Franche-Comté',
      "Vin de Pays des Côteaux de l'Auxois",
      'Vin de Pays des Côteaux de Coiffy',
      'Vin de Pays de Sainte-Marie-la-Blanche'
    ],
    'Languedoc-Roussillon' => [
      'Banyuls',
      'Banyuls Grand Cru',
      'Blanquette de Limoux',
      'Cabardès',
      'Cabrières',
      'Caramany',
      'Clairette de Bellegarde',
      'Clairette du Languedoc',
      'Collioure',
      'Corbières',
      'Costières de Nîmes',
      'Côteaux de la Mejanelle',
      'Côteaux de Saint-Christol',
      'Côteaux de Vérargues',
      'Côteaux du Languedoc',
      'Côtes de la Malepère',
      'Côtes du Roussillon',
      'Côtes du Roussillon Villages',
      'Crémant de Limoux',
      'Faugères',
      'Fitou',
      'Grand Roussillon',
      'Grès de Montpellier',
      'La Clape',
      'Latour de France',
      'Lesquerde',
      'Limoux',
      'Maury',
      'Minervois',
      'Minervois-la-Livinière',
      'Montpeyroux',
      'Muscat de Frontignon',
      'Muscat de Lunel',
      'Muscat de Mireval',
      'Muscat de Rivesaltes',
      'Muscat de Saint-Jean-de-Minervois',
      'Picpoul de Pinet',
      'Pic Saint Loup',
      'Quartouze',
      'Rivesaltes',
      'Saint-Chinian',
      'Saint-Drézéry',
      "Saint-Georges-d'Orques",
      'Saint-Saturnin',
      'Tautavel',
      "Vin de Pays de l'Aude",
      'Vin de Pays du Gard',
      "Vin de Pays de l'Herault",
      'Vin de Pays des Pyrénées-Orientales',
      'Vin de Pays Cathare',
      'Vin de Pays de la Cité de Carcassonne',
      'Vin de Pays des Côtes de Lastours',
      'Vin de Pays des Côtes de Pérignan',
      'Vin de Pays des Côtes de Prouilhes',
      'Vin de Pays des Coteaux de la Caberisse',
      'Vin de Pays des Coteaux de Miramont',
      'Vin de Pays des Coteaux de Narbonne',
      'Vin de Pays des Coteaux de Peyriac',
      'Vin de Pays des Coteaux du Littoral Audois',
      'Vin de Pays de Cucugnan',
      "Vin de Pays d'Hauterive",
      "Vin de Pays de la Haute Vallée de l'Aude",
      'Vin de Pays des Hauts de Badens',
      'Vin de Pays du Torgan',
      'Vin de Pays du Val de Cesse',
      'Vin de Pays du Val de Dagne',
      'Vin de Pays de la Vallée du Paradis',
      'Vin de Pays des Cévennes',
      'Vin de Pays des Côtes du Vidourle',
      'Vin de Pays des Coteaux de Cèze',
      'Vin de Pays des Coteaux Flaviens',
      'Vin de Pays des Coteaux du Pont du Gard',
      "Vin de Pays du Duché d'Uzès",
      'Vin de Pays des Sables du Golfe du Lion',
      'Vin de Pays de la Vaunage',
      'Vin de Pays de la Vistrenque',
      "Vin de Pays de l'Ardailhou",
      'Vin de Pays de la Bénovie',
      'Vin de Pays de Bérange',
      'Vin de Pays de Bessan',
      'Vin de Pays de Cassan',
      'Vin de Pays de Caux',
      'Vin de Pays de Cessenon',
      'Vin de Pays des Collines de la Moure',
      'Vin de Pays des Côtes de Brian',
      'Vin de Pays des Côtes du Ceressou',
      'Vin de Pays des Côtes de Thau',
      'Vin de Pays des Côtes de Thongue',
      'Vin de Pays des Coteaux de Bessilles',
      "Vin de Pays des Coteaux d'Enserune",
      'Vin de Pays des Coteaux de Fontcaude',
      'Vin de Pays des Coteaux de Laurens',
      'Vin de Pays des Coteaux du Libron',
      'Vin de Pays des Coteaux de Murviel',
      'Vin de Pays des Coteaux de Peyriac',
      'Vin de Pays des Coteaux du Salagou',
      "Vin de Pays de la Haute Vallée de l'Orb",
      'Vin de Pays du Mont Baudile',
      'Vin de Pays des Monts de la Grage',
      'Vin de Pays du Val de Montferrand',
      "Vin de Pays de la Vicomté d'Aumelas",
      'Vin de Pays de Saint-Guilhem Le Désert',
      'Vin de Pays Catalan',
      'Vin de Pays des Côtes Catalanes',
      'Vin de Pays de la Côte Vermeille',
      'Vin de Pays des Coteaux de Fenouillèdes',
      "Vin de Pays des Vals d'Agly",
      "Vin de Pays d'Oc",
      'Côtes du Roussillon - Les Aspres'
    ],
    'Provence' => [
      'Bandol',
      'Bellet',
      'Cassis',
      "Côteaux d'Aix-en-Provence",
      'Côteaux de Pierrevert',
      'Côteaux Varois',
      'Côtes de Provence',
      'Les Baux de Provence',
      'Palette',
      'Côtes de Provence Sainte-Victoire',
      'Côtes de Provence Fréjus'
    ],
    'Corse' => [
      'Ajaccio',
      'Muscat du Cap-Corse',
      'Patrimonio',
      'Vin de Corse',
      'Vin de Corse-Calvi',
      'Vin de Corse-Côteaux du Cap-Corse',
      'Vin de Corse-Figari',
      'Vin de Corse-Porto Vecchio',
      'Vin de Corse-Sartène',
      "Vin de Pays de l'Ile de Beauté",
    ],
    'Savoie' => [
      'Crépy',
      'Roussette de Savoie',
      'Roussette de Savoie Cru',
      'Roussette du Bugey',
      'Roussette du Bugey Cru',
      'Seyssel',
      'Vin de Savoie',
      'Vin de Savoie Cru',
      'Vin de Savoie-Ayze',
      'Vin du Bugey',
      'Vin du Bugey-Cru',
      "Vin de Pays d'Allobrogie",
      'Vin de Pays des Coteaux du Grésivaudan'
    ],
    'Sud-Ouest' => [
      'Béarn',
      'Bergerac',
      'Buzet',
      'Cahors',
      'Côteaux du Quercy',
      'Côtes de Bergerac',
      'Côtes de Duras',
      'Côtes de Millau',
      'Côtes de Montravel',
      'Côtes de Saint-Mont',
      'Côtes de Brulhois',
      'Fronton',
      'Côtes du Marmandais',
      'Floc de Gascogne',
      'Gaillac',
      'Gaillac Premières Côtes',
      'Haut-Montravel',
      'Irouleguy',
      'Jurançon',
      'Madiran',
      'Marcillac',
      'Monbazillac',
      'Montravel',
      'Pacherenc du Vic Bilh',
      'Pécharmant',
      'Rosette',
      'Saussignac',
      'Tursan',
      'Vin de Lavilledieu',
      "Vin d'Entraygues et du Fel",
      "Vins d'Estaing",
      'Vin de Pays des Landes',
      'Vin de Pays du Lot-et-Garonne',
      'Vin de Pays des Pyrénées-Atlantiques',
      "Vin de Pays de l'Agenais",
      'Vin de Pays du Périgord',
      'Vin de Pays des Terroirs Landais',
      'Vin de Pays de Thézac-Perricard',
      "Vin de Pays de l'Ariège",
      'Vin de Pays du Gers',
      'Vin de Pays de Haute-Garonne',
      'Vin de Pays des Hautes-Pyrénées',
      'Vin de Pays du Lot',
      'Vin de Pays du Tarn',
      'Vin de Pays du Tarn et Garonne',
      'Vin de Pays de Bigorre',
      'Vin de Pays des Côtes du Condomois',
      'Vin de Pays des Côtes de Gascogne',
      'Vin de Pays des Côtes du Tarn',
      'Vin de Pays des Coteaux de Glanes',
      'Vin de Pays des Coteaux et Terrasses de Montauban',
      'Vin de Pays de Montestruc',
      'Vin de Pays de Saint-Sardos',
      'Vin de Pays du Comté Tolosan',
      'Saint Sardos'
    ],
    'Vallée de la Loire' => [
      'Anjou',
      'Anjou-Côteaux de la Loire',
      'Anjou Gamay',
      'Anjou Mousseux',
      'Anjou-Villages',
      'Anjou-Villages Brissac',
      'Bonnezeaux',
      'Bourgueil',
      "Cabernet d'Anjou",
      'Cabernet de Saumur',
      'Châteaumeillant',
      'Cheverny',
      'Chinon',
      "Côteaux d'Ancenis",
      "Côteaux de l'Aubance",
      'Côteaux de Saumur',
      'Côteaux du Giennois',
      'Côteaux du Layon',
      'Côteaux du Layon Villages',
      'Chaume',
      'Côteaux du Loir',
      'Côteaux du Vendomois',
      'Côte Roannaise',
      "Côtes d'Auvergne",
      'Côtes du Forez',
      'Cour-Cheverny',
      'Crémant de Loire',
      'Gros Plant du Pays Nantais',
      'Jasnières',
      'Menetou-Salon',
      'Montlouis-sur-Loire',
      'Muscadet',
      'Muscadet-Côteaux de la Loire',
      'Muscadet-Côtes de Grandlieu',
      'Muscadet-Sevre et Maine',
      'Orléans',
      'Orléans-Cléry',
      'Pouilly Fumé',
      'Pouilly sur Loire',
      'Quarts de Chaume',
      'Quincy',
      'Reuilly',
      "Rosé d'Anjou",
      'Rosé de Loire',
      'Saint Nicolas de Bourgueil',
      'Saint Pourçain',
      'Sancerre',
      'Saumur',
      'Saumur-Champigny',
      'Saumur Mousseux',
      'Savennières',
      'Touraine',
      'Touraine-Amboise',
      'Touraine-Azay le Rideau',
      'Touraine-Mesland',
      'Touraine-Noble Joué',
      'Valençay',
      'Vouvray',
      "Vin de Pays de l'Allier",
      'Vin de Pays du Cher',
      'Vin de Pays des Deux-Sèvres',
      "Vin de Pays de l'Indre",
      "Vin de Pays d'Indre-et-Loire",
      'Vin de Pays de Loire-Atlantique',
      'Vin de Pays du Loiret',
      'Vin de Pays du Loir-et-Cher',
      'Vin de Pays du Maine-et-Loire',
      'Vin de Pays de la Nièvre',
      'Vin de Pays de la Sarthe',
      'Vin de Pays de Vendée',
      'Vin de Pays de la Vienne',
      'Vin de Pays de Retz',
      'Vin de Pays des Marchés de Bretagne',
      'Vin de Pays du Bourbonnais',
      'Vin de Pays des Côteaux Charitois',
      "Vin de Pays des Côteaux du Cher et de L'Arnon",
      'Vin de Pays du Jardin de la France',
      "Vin de Pays d'Urfé",
      'Chaume 1er Cru des Côteaux du Layon',
      'Vin de Pays des Côteaux de Tannay'
    ],
    'Vallée du Rhône' => [
      'Château Grillet',
      'Châteauneuf du Pape',
      'Chatillon en Diois',
      'Clairette de Die',
      'Condrieu',
      'Cornas',
      'Côteaux de Die',
      'Côteaux du Lyonnais',
      'Côteaux du Tricastin',
      'Côte Rotie',
      'Côtes du Lubéron',
      'Côtes du Rhône',
      'Côtes du Rhône Villages',
      'Côtes du Ventoux',
      'Côtes du Vivarais',
      'Crémant de Die',
      'Crozes-Hermitage',
      'Gigondas',
      'Hermitage',
      'Muscat des Beaumes de Venise',
      'Rasteau',
      'Saint Joseph',
      'Saint Péray',
      'Vacqueyras',
      'Lirac',
      'Tavel',
      'Vin de Pays des Alpes de Haute Provence',
      'Vin de Pays des Alpes Maritimes',
      'Vin de Pays des Bouches-du-Rhône',
      'Vin de Pays des Hautes-Alpes',
      'Vin de Pays du Vaucluse',
      'Vin de Pays du Var',
      "Vin de Pays d'Aigues",
      "Vin de Pays d'Argens",
      'Vin de Pays des Coteaux du Verdon',
      'Vin de Pays des Maures',
      'Vin de Pays de Mont Caume',
      'Vin de Pays de la Petite Crau',
      "Vin de Pays de la Principauté d'Orange",
      'Vin de Pays Portes de la Méditerranée',
      "Vin de Pays de l'Ardèche",
      'Vin de Pays de la Drôme',
      "Vin de Pays de l'Isère",
      'Vin de Pays des Balmes Dauphinoises',
      'Vin de Pays des Collines Rhodaniennes',
      'Vin de Pays du Comté de Grignan',
      "Vin de Pays des Coteaux de L'Ardèche",
      'Vin de Pays des Coteaux des Baronnies',
      'Beaumes de Venise'
    ]
  }
}.each do |s_country, regions|
  country = Country.find_or_create_by_name(s_country)
  regions.each do |s_region, areas|
    region = Region.find_or_create_by_name(s_region)
    region.country =  country
    region.save
    areas.each do |s_area|
      area = Area.find_or_create_by_name(s_area)
      area.region = region
      area.save
      puts "#{country.name}(#{country.id}) - #{region.name}(#{region.id}) - #{area.name}(#{area.id})"
    end
  end
end

